### ISSUE TITLE
`load_tree` doesn't work on specific file input

### ISSUE THREAD

**Issue by rmcar17** [cogent3/cogent3#1984]
`load_tree` no longer works on a specific tree file. Below is an example file:

[bad.txt](https://github.com/user-attachments/files/16576860/bad.txt)

Running the following:
```python
from cogent3 import load_tree
load_tree("bad.txt")
```

Gives the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rmcar17/miniconda3/envs/scs/lib/python3.12/site-packages/cogent3/__init__.py", line 752, in load_tree
    return make_tree(treestring, format=format, underscore_unmunge=underscore_unmunge)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmcar17/miniconda3/envs/scs/lib/python3.12/site-packages/cogent3/__init__.py", line 709, in make_tree
    tree = parser(treestring, tree_builder, underscore_unmunge=underscore_unmunge)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmcar17/miniconda3/envs/scs/lib/python3.12/site-packages/cogent3/parse/newick.py", line 149, in parse_string
    raise TreeParseError(f'Not a Newick tree: "{text[:10]}"')
cogent3.parse.newick.TreeParseError: Not a Newick tree: "愨戬㬩"
```

It did work in the `2024.7.19a1` release but failed somewhere between that and the `2024.7.19a3` release.

**Comment by rmcar17** [comment]
This is an issue with `charset-normalizer`, solution is to revert to `chardet` for now
